name: Pro Build & Release
on:
  workflow_dispatch:
    inputs:
      input_zip:
        description: 'Path to input .zip within repo'
        default: 'input/project.zip'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh "${{ github.event.inputs.input_zip || 'input/project.zip' }}"

      - name: Upload artifacts (always)
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: ./*/Assets/*

      - name: Publish GitHub Release (tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./*/Assets/*
          draft: false
          fail_on_unmatched_files: true
